# 
# Builder
FROM node:18-buster as builder
WORKDIR /src

# Deps
COPY package.json .
RUN npm install ci

# 
# Runtime
FROM node:18-alpine as runtime
WORKDIR /function

COPY --from=builder /src/node_modules ./node_modules
COPY . .

ENTRYPOINT [ "npm", "run", "start" ]